---
- name: Install misc stuff - Midnight commander, wget, Python MySQL, openssl
  vars:
    packages_Suse: ['mc', 'wget', 'python-mysql', 'openssl']
    packages_RedHat: ['mc', 'wget', 'MySQL-python',
                      'yum-utils', 'unzip', 'openssl',
                      'syslinux', 'sdparm', 'hdparm',
                      'redhat-lsb-core', 'lsof']
    # syslinux-utils is for gethostip, libpython is required for collectd
    packages_Debian: ['mc',
                      'wget',
                      'python-mysqldb',
                      'openssl',
                      'syslinux-utils',
                      'libpython2.7']
  package: name={{ item }} state=present
  with_items: "{{ vars['packages_' + ansible_os_family] }}"
