---
language: minimal

services:
  - docker

before_install:
  - docker pull retr0h/molecule:latest

script:
  - docker run --rm -it
     -v "$(pwd)":/tmp/$(basename "${PWD}"):ro
     -v /var/run/docker.sock:/var/run/docker.sock
     -w /tmp/$(basename "${PWD}")
     retr0h/molecule:latest
     molecule test -s lint
  - docker run --rm -it
     -v "$(pwd)":/tmp/$(basename "${PWD}"):ro
     -v /var/run/docker.sock:/var/run/docker.sock
     -w /tmp/$(basename "${PWD}")
     retr0h/molecule:latest
     sudo molecule test -s common


matrix:
  fast_finish: true
